[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
    \.vscode
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \venv
  | venv
  | _build
  | buck-out
  | build
  | dist
)/
'''